
rules-help::
	@echo
	@echo "** Help for users of BUILD_ITEM_RULES=contrib-pkg-config **"
	@echo
	@echo "This build item (contrib-pkg-config) provides support for"
	@echo "generation of interface files for packages configured with"
	@echo "pkg-config."
	@echo
	@echo "The following variable must be set:"
	@echo
	@echo " * PKG_CONFIG_PACKAGE -- the name of the package for pkg-config"
	@echo
	@echo "The following optional variables may be set:"
	@echo
	@echo " * PKG_CONFIG_PC_DIR -- the name of the directory in which to"
	@echo "   find the .pc files.  This can be set for testing and to access"
	@echo "   .pc files are not installed in standard locations known by"
	@echo "   pkg-config."
	@echo " * PKG_CONFIG_INTERFACE -- the name of the after-build interface"
	@echo "   file to create.  The default is pkg-config.interface.  It may"
	@echo "   be useful to override this if you wish to do postprocessing"
	@echo "   on the file"
	@echo

interface-help::
	@echo
	@echo "** Help for Abuild.interface for contrib-pkg-config build items **"
	@echo
	@echo "By default, a file called pkg-config.interface is generated by"
	@echo "users of the contrib-pkg-config build item.  Usually, you just"
	@echo "have to include"
	@echo
	@echo -n '  after-build $$'
	@echo '(ABUILD_OUTPUT_DIR)/pkg-config.interface'
	@echo
	@echo "in your Abuild.interface file to make the results visible to"
	@echo "your users."
	@echo

_UNDEFINED := $(call undefined_vars,PKG_CONFIG_PACKAGE)
ifneq ($(words $(_UNDEFINED)),0)
$(error The following variables are undefined: $(_UNDEFINED))
endif

PKG_CONFIG_PC_DIR ?=
PKG_CONFIG_INTERFACE ?= pkg-config.interface

all:: $(PKG_CONFIG_INTERFACE) ;

$(PKG_CONFIG_INTERFACE):
	@$(PRINT) Generating $@
	$(abDIR_contrib-pkg-config)/gen_interface \
	   $(PKG_CONFIG_PACKAGE) "$(PKG_CONFIG_PC_DIR)" $(PKG_CONFIG_INTERFACE)
